language: node_js

node_js:
  - 9.3.0

services:
  - docker

after_success:
  - docker build -t joaopio/front-end .
  - docker login -u "$DOCKER_USERNAME" -p "$DOCKER_PASSWORD"
  - docker push joaopio/front-end